using Eve.Shared.Config;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace Eve.DataGridControls
{
    /// <summary>
    /// Interaction logic for DataGridControlEvent.xaml
    /// </summary>
    public partial class DataGridControlEvent : UserControl
    {
        public DataGridControlElementEvent DataGridControlElementEvent
        {
            get; set;
        }
        public DataGridControlEvent(DataGridControlElementEvent dataGridControlElementEvent) : base()
        {
            InitializeComponent();
            this.DataGridControlElementEvent = dataGridControlElementEvent;
            DataGridControlElementEvent.DataGrid = DataGrid;
            DataGridControlElementEvent.PageInfo = PageInfo;
            InitializeButtons();
            DataGridShow();
        }

        private async void DataGridShow()
        {
            await DataGridControlElementEvent.Show();
        }

        private void InitializeButtons()
        {
            Helpers.ButtonContentHelper.SetContent(First, language.FirstPageButton);
            Helpers.ButtonContentHelper.SetContent(Last, language.LastPageButton);
            Helpers.ButtonContentHelper.SetContent(Backwards, language.BackwardsButton);
            Helpers.ButtonContentHelper.SetContent(Forward, language.ForwardButton);

        }


        
        private async void Backwards_Click(object sender, RoutedEventArgs e)
        {
                await DataGridControlElementEvent.Backwards_Click(sender, e);
        }
        

        private async void First_Click(object sender, RoutedEventArgs e)
        {
            await DataGridControlElementEvent.First_Click(sender, e);
        }

        private async void Last_Click(object sender, RoutedEventArgs e)
        {
            await DataGridControlElementEvent.Last_Click(sender, e);
        }

        private async void Forward_Click(object sender, RoutedEventArgs e)
        {
            await DataGridControlElementEvent.Forward_Click(sender, e);
        }
        public void ClearSelectedItems()
        {
            for (int i = 0; i < DataGrid.SelectedItems.Count; ++i)
            {
                DataGrid.SelectedItems.RemoveAt(i);
            }
        }
        public async void Refresh()
        {
            //await DataGridControlElementEvent.First_Click(null, null);
            await DataGridControlElementEvent.Refresh();
        }

        private void DataGrid_AutoGeneratedColumns(object sender, System.EventArgs e)
        {
            DataGridControlElementEvent.InitializeColumns();
        }

    }
}
