using System.Windows;
using System.Windows.Controls;
using Eve.Shared.Config;

namespace Eve.DataGridControls
{
    /// <summary>
    /// Interaction logic for DataGridControl.xaml
    /// </summary>
    public partial class DataGridControl : UserControl
    {

        public DataGridControlElement DataGridControlElement
        {
            get; set;
        }

        public DataGridControl(DataGridControlElement dataGridControlElement) : base()
        {
            InitializeComponent();
            this.DataGridControlElement = dataGridControlElement;
            DataGridControlElement.DataGrid = DataGrid;
            DataGridControlElement.PageInfo = PageInfo;
            InitializeButtons();
            DataGridShow();
        }

        private async void DataGridShow()
        {
            await DataGridControlElement.Show();
        }

        private void InitializeButtons()
        {
            Helpers.ButtonContentHelper.SetContent(First, "<< First");
            Helpers.ButtonContentHelper.SetContent(Last, "Last >>");
            Helpers.ButtonContentHelper.SetContent(Backwards, "< Backwards");
            Helpers.ButtonContentHelper.SetContent(Forward, "Forwards >");

        }

        private async void Last_Click(object sender, RoutedEventArgs e)
        {
            await DataGridControlElement.Last_Click(sender, e);
        }

        private async void Forward_Click(object sender, RoutedEventArgs e)
        {
            await DataGridControlElement.Forward_Click(sender, e);
        }

        private async void Backwards_Click(object sender, RoutedEventArgs e)
        {
            await DataGridControlElement.Backwards_Click(sender, e);
        }

        private async void First_Click(object sender, RoutedEventArgs e)
        {
            await DataGridControlElement.First_Click(sender, e);
        }




        public void ClearSelectedItems()
        {
            for (int i = 0; i < DataGrid.SelectedItems.Count; ++i)
            {
                DataGrid.SelectedItems.RemoveAt(i);
            }
        }
        public async void Refresh()
        {
            //await DataGridControlElement.First_Click(null, null);
            await DataGridControlElement.Refresh();
        }

        private void DataGrid_AutoGeneratedColumns(object sender, System.EventArgs e)
        {
            DataGridControlElement.InitializeColumns();
        }
    }
}
